apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate 
metadata:
  name: my-template
spec:
  entrypoint: hello
  templates:
  - name: hello
    container:
      image: python:3.9-slim
      command: ["python"]
      args: ["-c", "print('hello world')"]
