apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate 
metadata:
  name: my-template
spec:
  entrypoint: test
  templates:
  - name: test
    container:
      image: busybox:1.36
      command: ["echo"]
      args: ["hello world"]
