apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate 
metadata:
  name: my-template
spec:
  entrypoint: hello
  templates:
  - name: hello
    container:
      image: alpine:3.19
      command: [sh, -c]
      args: ["echo 'hello world' && uname -a"]
